// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/scanner.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_CLibraryPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCLibraryPtr;

  @protected
  CLibrary
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCLibrary(
    dynamic raw,
  );

  @protected
  CLibrary
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCLibrary(
    dynamic raw,
  );

  @protected
  CLibrary
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCLibrary(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AlbumViewData dco_decode_album_view_data(dynamic raw);

  @protected
  ArtistViewData dco_decode_artist_view_data(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ArtistViewData dco_decode_box_autoadd_artist_view_data(dynamic raw);

  @protected
  Config dco_decode_box_autoadd_config(dynamic raw);

  @protected
  PlaybackStateData dco_decode_box_autoadd_playback_state_data(dynamic raw);

  @protected
  SongViewData dco_decode_box_autoadd_song_view_data(dynamic raw);

  @protected
  Config dco_decode_config(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AlbumViewData> dco_decode_list_album_view_data(dynamic raw);

  @protected
  List<ArtistViewData> dco_decode_list_artist_view_data(dynamic raw);

  @protected
  List<PlaylistViewData> dco_decode_list_playlist_view_data(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SongViewData> dco_decode_list_song_view_data(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  ArtistViewData? dco_decode_opt_box_autoadd_artist_view_data(dynamic raw);

  @protected
  PlaybackStateData? dco_decode_opt_box_autoadd_playback_state_data(
    dynamic raw,
  );

  @protected
  SongViewData? dco_decode_opt_box_autoadd_song_view_data(dynamic raw);

  @protected
  PlaybackStateData dco_decode_playback_state_data(dynamic raw);

  @protected
  PlaylistViewData dco_decode_playlist_view_data(dynamic raw);

  @protected
  SongViewData dco_decode_song_view_data(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  CLibrary
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCLibrary(
    SseDeserializer deserializer,
  );

  @protected
  CLibrary
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCLibrary(
    SseDeserializer deserializer,
  );

  @protected
  CLibrary
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCLibrary(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AlbumViewData sse_decode_album_view_data(SseDeserializer deserializer);

  @protected
  ArtistViewData sse_decode_artist_view_data(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ArtistViewData sse_decode_box_autoadd_artist_view_data(
    SseDeserializer deserializer,
  );

  @protected
  Config sse_decode_box_autoadd_config(SseDeserializer deserializer);

  @protected
  PlaybackStateData sse_decode_box_autoadd_playback_state_data(
    SseDeserializer deserializer,
  );

  @protected
  SongViewData sse_decode_box_autoadd_song_view_data(
    SseDeserializer deserializer,
  );

  @protected
  Config sse_decode_config(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AlbumViewData> sse_decode_list_album_view_data(
    SseDeserializer deserializer,
  );

  @protected
  List<ArtistViewData> sse_decode_list_artist_view_data(
    SseDeserializer deserializer,
  );

  @protected
  List<PlaylistViewData> sse_decode_list_playlist_view_data(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SongViewData> sse_decode_list_song_view_data(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  ArtistViewData? sse_decode_opt_box_autoadd_artist_view_data(
    SseDeserializer deserializer,
  );

  @protected
  PlaybackStateData? sse_decode_opt_box_autoadd_playback_state_data(
    SseDeserializer deserializer,
  );

  @protected
  SongViewData? sse_decode_opt_box_autoadd_song_view_data(
    SseDeserializer deserializer,
  );

  @protected
  PlaybackStateData sse_decode_playback_state_data(
    SseDeserializer deserializer,
  );

  @protected
  PlaylistViewData sse_decode_playlist_view_data(SseDeserializer deserializer);

  @protected
  SongViewData sse_decode_song_view_data(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCLibrary(
    CLibrary self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCLibrary(
    CLibrary self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCLibrary(
    CLibrary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_album_view_data(AlbumViewData self, SseSerializer serializer);

  @protected
  void sse_encode_artist_view_data(
    ArtistViewData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_artist_view_data(
    ArtistViewData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_config(Config self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_playback_state_data(
    PlaybackStateData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_song_view_data(
    SongViewData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_config(Config self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_album_view_data(
    List<AlbumViewData> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_artist_view_data(
    List<ArtistViewData> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_playlist_view_data(
    List<PlaylistViewData> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_song_view_data(
    List<SongViewData> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_artist_view_data(
    ArtistViewData? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_playback_state_data(
    PlaybackStateData? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_song_view_data(
    SongViewData? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_playback_state_data(
    PlaybackStateData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_playlist_view_data(
    PlaylistViewData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_song_view_data(SongViewData self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCLibrary(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCLibrary(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCLibraryPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_clutter_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCLibrary',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCLibrary =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCLibraryPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCLibrary(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCLibrary(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCLibraryPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_clutter_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCLibrary',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCLibrary =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCLibraryPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
