// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/library.dart';
import 'api/models.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_LibraryApiPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryApi;

  @protected
  LibraryApi
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryApi(
    dynamic raw,
  );

  @protected
  LibraryApi
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryApi(
    dynamic raw,
  );

  @protected
  LibraryApi
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryApi(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AlbumChoice dco_decode_album_choice(dynamic raw);

  @protected
  AlbumEditRequest dco_decode_album_edit_request(dynamic raw);

  @protected
  AlbumViewData dco_decode_album_view_data(dynamic raw);

  @protected
  ArtistViewData dco_decode_artist_view_data(dynamic raw);

  @protected
  ArtworkCropRectData dco_decode_artwork_crop_rect_data(dynamic raw);

  @protected
  ArtworkEditData dco_decode_artwork_edit_data(dynamic raw);

  @protected
  ArtworkOwner dco_decode_artwork_owner(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AlbumEditRequest dco_decode_box_autoadd_album_edit_request(dynamic raw);

  @protected
  ArtistViewData dco_decode_box_autoadd_artist_view_data(dynamic raw);

  @protected
  ArtworkCropRectData dco_decode_box_autoadd_artwork_crop_rect_data(
    dynamic raw,
  );

  @protected
  ArtworkEditData dco_decode_box_autoadd_artwork_edit_data(dynamic raw);

  @protected
  CoverArtEdit dco_decode_box_autoadd_cover_art_edit(dynamic raw);

  @protected
  ExtractedSongCropRequest dco_decode_box_autoadd_extracted_song_crop_request(
    dynamic raw,
  );

  @protected
  ExtractedSongImportRequest
  dco_decode_box_autoadd_extracted_song_import_request(dynamic raw);

  @protected
  KeybindingData dco_decode_box_autoadd_keybinding_data(dynamic raw);

  @protected
  PlaybackStateData dco_decode_box_autoadd_playback_state_data(dynamic raw);

  @protected
  PlaylistEditRequest dco_decode_box_autoadd_playlist_edit_request(dynamic raw);

  @protected
  ScanConfig dco_decode_box_autoadd_scan_config(dynamic raw);

  @protected
  SongCropData dco_decode_box_autoadd_song_crop_data(dynamic raw);

  @protected
  SongEditRequest dco_decode_box_autoadd_song_edit_request(dynamic raw);

  @protected
  SongViewData dco_decode_box_autoadd_song_view_data(dynamic raw);

  @protected
  CoverArtEdit dco_decode_cover_art_edit(dynamic raw);

  @protected
  ExtractedSongCropRequest dco_decode_extracted_song_crop_request(dynamic raw);

  @protected
  ExtractedSongImportRequest dco_decode_extracted_song_import_request(
    dynamic raw,
  );

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  KeybindingAction dco_decode_keybinding_action(dynamic raw);

  @protected
  KeybindingData dco_decode_keybinding_data(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AlbumViewData> dco_decode_list_album_view_data(dynamic raw);

  @protected
  List<ArtistViewData> dco_decode_list_artist_view_data(dynamic raw);

  @protected
  List<KeybindingData> dco_decode_list_keybinding_data(dynamic raw);

  @protected
  List<PinnedItemData> dco_decode_list_pinned_item_data(dynamic raw);

  @protected
  List<PlaylistViewData> dco_decode_list_playlist_view_data(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SongViewData> dco_decode_list_song_view_data(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  ArtistViewData? dco_decode_opt_box_autoadd_artist_view_data(dynamic raw);

  @protected
  ArtworkEditData? dco_decode_opt_box_autoadd_artwork_edit_data(dynamic raw);

  @protected
  ExtractedSongCropRequest?
  dco_decode_opt_box_autoadd_extracted_song_crop_request(dynamic raw);

  @protected
  PlaybackStateData? dco_decode_opt_box_autoadd_playback_state_data(
    dynamic raw,
  );

  @protected
  SongCropData? dco_decode_opt_box_autoadd_song_crop_data(dynamic raw);

  @protected
  SongViewData? dco_decode_opt_box_autoadd_song_view_data(dynamic raw);

  @protected
  PinnedItemData dco_decode_pinned_item_data(dynamic raw);

  @protected
  PlaybackStateData dco_decode_playback_state_data(dynamic raw);

  @protected
  PlaylistEditRequest dco_decode_playlist_edit_request(dynamic raw);

  @protected
  PlaylistViewData dco_decode_playlist_view_data(dynamic raw);

  @protected
  PlaylistVisualEdit dco_decode_playlist_visual_edit(dynamic raw);

  @protected
  ScanConfig dco_decode_scan_config(dynamic raw);

  @protected
  SongAudioEdit dco_decode_song_audio_edit(dynamic raw);

  @protected
  SongCropData dco_decode_song_crop_data(dynamic raw);

  @protected
  SongEditRequest dco_decode_song_edit_request(dynamic raw);

  @protected
  SongViewData dco_decode_song_view_data(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  LibraryApi
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryApi(
    SseDeserializer deserializer,
  );

  @protected
  LibraryApi
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryApi(
    SseDeserializer deserializer,
  );

  @protected
  LibraryApi
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryApi(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AlbumChoice sse_decode_album_choice(SseDeserializer deserializer);

  @protected
  AlbumEditRequest sse_decode_album_edit_request(SseDeserializer deserializer);

  @protected
  AlbumViewData sse_decode_album_view_data(SseDeserializer deserializer);

  @protected
  ArtistViewData sse_decode_artist_view_data(SseDeserializer deserializer);

  @protected
  ArtworkCropRectData sse_decode_artwork_crop_rect_data(
    SseDeserializer deserializer,
  );

  @protected
  ArtworkEditData sse_decode_artwork_edit_data(SseDeserializer deserializer);

  @protected
  ArtworkOwner sse_decode_artwork_owner(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AlbumEditRequest sse_decode_box_autoadd_album_edit_request(
    SseDeserializer deserializer,
  );

  @protected
  ArtistViewData sse_decode_box_autoadd_artist_view_data(
    SseDeserializer deserializer,
  );

  @protected
  ArtworkCropRectData sse_decode_box_autoadd_artwork_crop_rect_data(
    SseDeserializer deserializer,
  );

  @protected
  ArtworkEditData sse_decode_box_autoadd_artwork_edit_data(
    SseDeserializer deserializer,
  );

  @protected
  CoverArtEdit sse_decode_box_autoadd_cover_art_edit(
    SseDeserializer deserializer,
  );

  @protected
  ExtractedSongCropRequest sse_decode_box_autoadd_extracted_song_crop_request(
    SseDeserializer deserializer,
  );

  @protected
  ExtractedSongImportRequest
  sse_decode_box_autoadd_extracted_song_import_request(
    SseDeserializer deserializer,
  );

  @protected
  KeybindingData sse_decode_box_autoadd_keybinding_data(
    SseDeserializer deserializer,
  );

  @protected
  PlaybackStateData sse_decode_box_autoadd_playback_state_data(
    SseDeserializer deserializer,
  );

  @protected
  PlaylistEditRequest sse_decode_box_autoadd_playlist_edit_request(
    SseDeserializer deserializer,
  );

  @protected
  ScanConfig sse_decode_box_autoadd_scan_config(SseDeserializer deserializer);

  @protected
  SongCropData sse_decode_box_autoadd_song_crop_data(
    SseDeserializer deserializer,
  );

  @protected
  SongEditRequest sse_decode_box_autoadd_song_edit_request(
    SseDeserializer deserializer,
  );

  @protected
  SongViewData sse_decode_box_autoadd_song_view_data(
    SseDeserializer deserializer,
  );

  @protected
  CoverArtEdit sse_decode_cover_art_edit(SseDeserializer deserializer);

  @protected
  ExtractedSongCropRequest sse_decode_extracted_song_crop_request(
    SseDeserializer deserializer,
  );

  @protected
  ExtractedSongImportRequest sse_decode_extracted_song_import_request(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  KeybindingAction sse_decode_keybinding_action(SseDeserializer deserializer);

  @protected
  KeybindingData sse_decode_keybinding_data(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AlbumViewData> sse_decode_list_album_view_data(
    SseDeserializer deserializer,
  );

  @protected
  List<ArtistViewData> sse_decode_list_artist_view_data(
    SseDeserializer deserializer,
  );

  @protected
  List<KeybindingData> sse_decode_list_keybinding_data(
    SseDeserializer deserializer,
  );

  @protected
  List<PinnedItemData> sse_decode_list_pinned_item_data(
    SseDeserializer deserializer,
  );

  @protected
  List<PlaylistViewData> sse_decode_list_playlist_view_data(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SongViewData> sse_decode_list_song_view_data(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  ArtistViewData? sse_decode_opt_box_autoadd_artist_view_data(
    SseDeserializer deserializer,
  );

  @protected
  ArtworkEditData? sse_decode_opt_box_autoadd_artwork_edit_data(
    SseDeserializer deserializer,
  );

  @protected
  ExtractedSongCropRequest?
  sse_decode_opt_box_autoadd_extracted_song_crop_request(
    SseDeserializer deserializer,
  );

  @protected
  PlaybackStateData? sse_decode_opt_box_autoadd_playback_state_data(
    SseDeserializer deserializer,
  );

  @protected
  SongCropData? sse_decode_opt_box_autoadd_song_crop_data(
    SseDeserializer deserializer,
  );

  @protected
  SongViewData? sse_decode_opt_box_autoadd_song_view_data(
    SseDeserializer deserializer,
  );

  @protected
  PinnedItemData sse_decode_pinned_item_data(SseDeserializer deserializer);

  @protected
  PlaybackStateData sse_decode_playback_state_data(
    SseDeserializer deserializer,
  );

  @protected
  PlaylistEditRequest sse_decode_playlist_edit_request(
    SseDeserializer deserializer,
  );

  @protected
  PlaylistViewData sse_decode_playlist_view_data(SseDeserializer deserializer);

  @protected
  PlaylistVisualEdit sse_decode_playlist_visual_edit(
    SseDeserializer deserializer,
  );

  @protected
  ScanConfig sse_decode_scan_config(SseDeserializer deserializer);

  @protected
  SongAudioEdit sse_decode_song_audio_edit(SseDeserializer deserializer);

  @protected
  SongCropData sse_decode_song_crop_data(SseDeserializer deserializer);

  @protected
  SongEditRequest sse_decode_song_edit_request(SseDeserializer deserializer);

  @protected
  SongViewData sse_decode_song_view_data(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryApi(
    LibraryApi self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryApi(
    LibraryApi self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryApi(
    LibraryApi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_album_choice(AlbumChoice self, SseSerializer serializer);

  @protected
  void sse_encode_album_edit_request(
    AlbumEditRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_album_view_data(AlbumViewData self, SseSerializer serializer);

  @protected
  void sse_encode_artist_view_data(
    ArtistViewData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_artwork_crop_rect_data(
    ArtworkCropRectData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_artwork_edit_data(
    ArtworkEditData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_artwork_owner(ArtworkOwner self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_album_edit_request(
    AlbumEditRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_artist_view_data(
    ArtistViewData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_artwork_crop_rect_data(
    ArtworkCropRectData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_artwork_edit_data(
    ArtworkEditData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_cover_art_edit(
    CoverArtEdit self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_extracted_song_crop_request(
    ExtractedSongCropRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_extracted_song_import_request(
    ExtractedSongImportRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_keybinding_data(
    KeybindingData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_playback_state_data(
    PlaybackStateData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_playlist_edit_request(
    PlaylistEditRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_scan_config(
    ScanConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_song_crop_data(
    SongCropData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_song_edit_request(
    SongEditRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_song_view_data(
    SongViewData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_cover_art_edit(CoverArtEdit self, SseSerializer serializer);

  @protected
  void sse_encode_extracted_song_crop_request(
    ExtractedSongCropRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_extracted_song_import_request(
    ExtractedSongImportRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_keybinding_action(
    KeybindingAction self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_keybinding_data(
    KeybindingData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_album_view_data(
    List<AlbumViewData> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_artist_view_data(
    List<ArtistViewData> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_keybinding_data(
    List<KeybindingData> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_pinned_item_data(
    List<PinnedItemData> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_playlist_view_data(
    List<PlaylistViewData> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_song_view_data(
    List<SongViewData> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_artist_view_data(
    ArtistViewData? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_artwork_edit_data(
    ArtworkEditData? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_extracted_song_crop_request(
    ExtractedSongCropRequest? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_playback_state_data(
    PlaybackStateData? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_song_crop_data(
    SongCropData? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_song_view_data(
    SongViewData? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pinned_item_data(
    PinnedItemData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_playback_state_data(
    PlaybackStateData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_playlist_edit_request(
    PlaylistEditRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_playlist_view_data(
    PlaylistViewData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_playlist_visual_edit(
    PlaylistVisualEdit self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_scan_config(ScanConfig self, SseSerializer serializer);

  @protected
  void sse_encode_song_audio_edit(SongAudioEdit self, SseSerializer serializer);

  @protected
  void sse_encode_song_crop_data(SongCropData self, SseSerializer serializer);

  @protected
  void sse_encode_song_edit_request(
    SongEditRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_song_view_data(SongViewData self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryApi(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryApi(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryApi(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryApi(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryApi(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibraryApi(
    int ptr,
  );
}
