// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

String spank({required String name}) =>
    RustLib.instance.api.crateApiComplexSpank(name: name);

Future<void> printHello({required Hello hello}) =>
    RustLib.instance.api.crateApiComplexPrintHello(hello: hello);

class Hello {
  final String name;

  const Hello({required this.name});

  @override
  int get hashCode => name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Hello && runtimeType == other.runtimeType && name == other.name;
}
