// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `abs_album`, `abs_artist`, `abs_song`, `absolutize`, `backup_user_playlists`, `cleanup_orphan_album`, `ensure_album`, `ensure_artist`, `ensure_liked_songs_playlist`, `guess_cover_ext`, `insert_song`, `like_escape`, `map_song_row`, `normalize_match_value`, `now_secs`, `playlist_is_user`, `query_albums_by_artist`, `query_albums`, `query_artists`, `query_playlists`, `query_songs`, `relativize`, `remove_album_row`, `restore_user_playlists_from_backup`, `search_albums`, `search_playlists`, `to_abs`, `to_rel`, `write_cover_if_missing`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AlbumRow`, `ArtistFilter`, `ArtistRow`, `PinnedItemRow`, `PlaybackStateRow`, `PlaylistRow`, `SongFilter`, `SongRow`, `Store`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `add_scan_path`, `add_song_to_playlist`, `create_playlist`, `delete_album`, `delete_playlist`, `delete_scan_path`, `delete_song`, `get_albums_artist_featured_on`, `get_albums_by_artist_id`, `get_albums_paginated`, `get_artist_by_id`, `get_artists_paginated`, `get_liked_song_ids`, `get_liked_songs_playlist_id`, `get_pinned_items`, `get_playlists_paginated`, `get_recently_played`, `get_scan_paths`, `get_song_by_id`, `get_songs_artist_featured_on`, `get_songs_by_album_id`, `get_songs_in_playlist`, `get_songs_paginated`, `get_total_albums`, `get_total_artists`, `get_total_playlists`, `get_total_songs`, `insert_song`, `load_playback_state`, `move_pinned_item`, `open`, `pin_item`, `record_play`, `remove_song_from_playlist`, `reset_library`, `restore_user_playlists_from_backup`, `save_playback_state`, `search_albums`, `search_artists`, `search_playlists`, `search_songs`, `split_album_to_new_artist`, `unpin_item`

class PlaylistBackup {
  final List<PlaylistBackupPlaylist> playlists;

  const PlaylistBackup({required this.playlists});

  static Future<PlaylistBackup> default_() =>
      RustLib.instance.api.crateApiDbPlaylistBackupDefault();

  @override
  int get hashCode => playlists.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaylistBackup &&
          runtimeType == other.runtimeType &&
          playlists == other.playlists;
}

class PlaylistBackupPlaylist {
  final String name;
  final List<PlaylistBackupSong> songs;

  const PlaylistBackupPlaylist({required this.name, required this.songs});

  @override
  int get hashCode => name.hashCode ^ songs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaylistBackupPlaylist &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          songs == other.songs;
}

class PlaylistBackupSong {
  final String title;
  final String album;

  const PlaylistBackupSong({required this.title, required this.album});

  @override
  int get hashCode => title.hashCode ^ album.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaylistBackupSong &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          album == other.album;
}
