// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LibraryApi>>
abstract class LibraryApi implements RustOpaqueInterface {
  Future<void> addSongToPlaylist({
    required String playlistId,
    required String songId,
  });

  Future<String> createPlaylist({required String name});

  Future<void> deleteAlbum({required String id});

  Future<void> deletePlaylist({required String id});

  /// Remove a scan path and every song indexed beneath it. Returns the
  /// number of songs purged so the UI can surface it in a toast.
  Future<int> deleteScanPath({required String path});

  Future<void> deleteSong({required String id});

  Future<List<AlbumViewData>> getAlbumsArtistFeaturedOn({
    required String artistId,
  });

  Future<List<AlbumViewData>> getAlbumsByArtistId({required String artistId});

  Future<List<AlbumViewData>> getAlbumsPaginated({
    required int offset,
    required int limit,
  });

  Future<ArtistViewData?> getArtistById({required String id});

  Future<List<ArtistViewData>> getArtistsPaginated({
    required int offset,
    required int limit,
  });

  Future<List<String>> getLikedSongIds();

  Future<String?> getLikedSongsPlaylistId();

  Future<List<PinnedItemData>> getPinnedItems();

  Future<List<PlaylistViewData>> getPlaylistsPaginated({
    required int offset,
    required int limit,
  });

  Future<List<SongViewData>> getRecentlyPlayed({required int limit});

  Future<List<String>> getScanPaths();

  Future<SongViewData?> getSongById({required String id});

  Future<List<SongViewData>> getSongsArtistFeaturedOn({
    required String artistId,
  });

  Future<List<SongViewData>> getSongsByAlbumId({required String albumId});

  Future<List<SongViewData>> getSongsInPlaylist({required String playlistId});

  Future<List<SongViewData>> getSongsPaginated({
    required int offset,
    required int limit,
  });

  int getTotalAlbums();

  int getTotalArtists();

  int getTotalPlaylists();

  int getTotalSongs();

  /// Open (or create) the SQLite database at `db_path` and ensure the covers
  /// directory exists. Must be called once from Dart before any other method.
  static Future<LibraryApi> init({
    required String dbPath,
    required String coversDir,
    required String baseDir,
  }) => RustLib.instance.api.crateApiLibraryLibraryApiInit(
    dbPath: dbPath,
    coversDir: coversDir,
    baseDir: baseDir,
  );

  Future<PlaybackStateData?> loadPlaybackState();

  Future<void> movePinnedItem({
    required String itemId,
    required String kind,
    required int newIndex,
  });

  Future<void> pinItem({required String itemId, required String kind});

  Future<void> recordPlay({required String songId});

  Future<void> removeSongFromPlaylist({
    required String playlistId,
    required String songId,
  });

  Future<void> resetLibrary();

  Future<void> savePlaybackState({
    String? songId,
    required PlatformInt64 positionMs,
    required bool loopOne,
  });

  /// Recursively scan `path` for audio files and write their metadata into
  /// SQLite. Files already present (matched by `file_path`) are skipped.
  Future<void> scanDirectory({
    required String path,
    required ScanConfig config,
  });

  Future<List<AlbumViewData>> searchAlbums({
    required String query,
    required int limit,
  });

  Future<List<ArtistViewData>> searchArtists({
    required String query,
    required int limit,
  });

  Future<List<PlaylistViewData>> searchPlaylists({
    required String query,
    required int limit,
  });

  Future<List<SongViewData>> searchSongs({
    required String query,
    required int limit,
  });

  /// Fork an album onto a freshly-created artist row with the same name.
  /// Returns the new artist's id. Used by the UI to resolve ambiguity when
  /// the scanner merged two distinct same-named artists into one row.
  Future<String> splitAlbumToNewArtist({required String albumId});

  Future<void> unpinItem({required String itemId, required String kind});

  Future<AlbumViewData> updateAlbum({required AlbumEditRequest request});

  Future<ArtistViewData> updateArtistImage({
    required String artistId,
    required CoverArtEdit cover,
  });

  Future<PlaylistViewData> updatePlaylist({
    required PlaylistEditRequest request,
  });

  Future<SongViewData> updateSong({required SongEditRequest request});
}
