// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'models.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `as_str`, `from_str`, `into_internal`, `into_row`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

@freezed
sealed class AlbumChoice with _$AlbumChoice {
  const AlbumChoice._();

  const factory AlbumChoice.existing({required String albumId}) =
      AlbumChoice_Existing;
  const factory AlbumChoice.new_({
    required String title,
    required List<String> artists,
  }) = AlbumChoice_New;
}

class AlbumEditRequest {
  final String albumId;
  final String title;
  final List<String> artists;
  final CoverArtEdit cover;

  const AlbumEditRequest({
    required this.albumId,
    required this.title,
    required this.artists,
    required this.cover,
  });

  @override
  int get hashCode =>
      albumId.hashCode ^ title.hashCode ^ artists.hashCode ^ cover.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AlbumEditRequest &&
          runtimeType == other.runtimeType &&
          albumId == other.albumId &&
          title == other.title &&
          artists == other.artists &&
          cover == other.cover;
}

class AlbumViewData {
  final String id;
  final String title;
  final String artist;
  final String? coverPath;
  final PlatformInt64 songCount;
  final List<String> artists;

  const AlbumViewData({
    required this.id,
    required this.title,
    required this.artist,
    this.coverPath,
    required this.songCount,
    required this.artists,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      artist.hashCode ^
      coverPath.hashCode ^
      songCount.hashCode ^
      artists.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AlbumViewData &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          artist == other.artist &&
          coverPath == other.coverPath &&
          songCount == other.songCount &&
          artists == other.artists;
}

class ArtistViewData {
  final String id;
  final String name;
  final String? coverPath;
  final PlatformInt64 albumCount;
  final PlatformInt64 songCount;
  final String? customCoverPath;

  const ArtistViewData({
    required this.id,
    required this.name,
    this.coverPath,
    required this.albumCount,
    required this.songCount,
    this.customCoverPath,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      coverPath.hashCode ^
      albumCount.hashCode ^
      songCount.hashCode ^
      customCoverPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArtistViewData &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          coverPath == other.coverPath &&
          albumCount == other.albumCount &&
          songCount == other.songCount &&
          customCoverPath == other.customCoverPath;
}

class ArtworkCropRectData {
  final double left;
  final double top;
  final double width;
  final double height;

  const ArtworkCropRectData({
    required this.left,
    required this.top,
    required this.width,
    required this.height,
  });

  @override
  int get hashCode =>
      left.hashCode ^ top.hashCode ^ width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArtworkCropRectData &&
          runtimeType == other.runtimeType &&
          left == other.left &&
          top == other.top &&
          width == other.width &&
          height == other.height;
}

class ArtworkEditData {
  final String originalPath;
  final ArtworkCropRectData crop;

  const ArtworkEditData({required this.originalPath, required this.crop});

  @override
  int get hashCode => originalPath.hashCode ^ crop.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArtworkEditData &&
          runtimeType == other.runtimeType &&
          originalPath == other.originalPath &&
          crop == other.crop;
}

enum ArtworkOwner { song, album, artist, playlist }

@freezed
sealed class CoverArtEdit with _$CoverArtEdit {
  const CoverArtEdit._();

  const factory CoverArtEdit.keep() = CoverArtEdit_Keep;
  const factory CoverArtEdit.remove() = CoverArtEdit_Remove;
  const factory CoverArtEdit.replace({
    required String originalSourcePath,
    required String croppedSourcePath,
    required ArtworkCropRectData crop,
  }) = CoverArtEdit_Replace;
}

class ExtractedSongCropRequest {
  final String originalSourcePath;
  final PlatformInt64 startMs;
  final PlatformInt64 endMs;

  const ExtractedSongCropRequest({
    required this.originalSourcePath,
    required this.startMs,
    required this.endMs,
  });

  @override
  int get hashCode =>
      originalSourcePath.hashCode ^ startMs.hashCode ^ endMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExtractedSongCropRequest &&
          runtimeType == other.runtimeType &&
          originalSourcePath == other.originalSourcePath &&
          startMs == other.startMs &&
          endMs == other.endMs;
}

class ExtractedSongImportRequest {
  final String sourcePath;
  final String title;
  final String primaryArtist;
  final List<String> featuredArtists;
  final PlatformInt64 trackNum;
  final PlatformInt64 discNum;
  final AlbumChoice album;
  final CoverArtEdit cover;
  final ExtractedSongCropRequest? crop;

  const ExtractedSongImportRequest({
    required this.sourcePath,
    required this.title,
    required this.primaryArtist,
    required this.featuredArtists,
    required this.trackNum,
    required this.discNum,
    required this.album,
    required this.cover,
    this.crop,
  });

  @override
  int get hashCode =>
      sourcePath.hashCode ^
      title.hashCode ^
      primaryArtist.hashCode ^
      featuredArtists.hashCode ^
      trackNum.hashCode ^
      discNum.hashCode ^
      album.hashCode ^
      cover.hashCode ^
      crop.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExtractedSongImportRequest &&
          runtimeType == other.runtimeType &&
          sourcePath == other.sourcePath &&
          title == other.title &&
          primaryArtist == other.primaryArtist &&
          featuredArtists == other.featuredArtists &&
          trackNum == other.trackNum &&
          discNum == other.discNum &&
          album == other.album &&
          cover == other.cover &&
          crop == other.crop;
}

enum KeybindingAction { playPause, previousTrack, nextTrack, omniSearch }

class KeybindingData {
  final KeybindingAction action;
  final String? keyCode;
  final bool primary;
  final bool control;
  final bool meta;
  final bool alt;
  final bool shift;

  const KeybindingData({
    required this.action,
    this.keyCode,
    required this.primary,
    required this.control,
    required this.meta,
    required this.alt,
    required this.shift,
  });

  @override
  int get hashCode =>
      action.hashCode ^
      keyCode.hashCode ^
      primary.hashCode ^
      control.hashCode ^
      meta.hashCode ^
      alt.hashCode ^
      shift.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeybindingData &&
          runtimeType == other.runtimeType &&
          action == other.action &&
          keyCode == other.keyCode &&
          primary == other.primary &&
          control == other.control &&
          meta == other.meta &&
          alt == other.alt &&
          shift == other.shift;
}

class PinnedItemData {
  final String itemId;
  final String kind;
  final PlatformInt64 position;

  const PinnedItemData({
    required this.itemId,
    required this.kind,
    required this.position,
  });

  @override
  int get hashCode => itemId.hashCode ^ kind.hashCode ^ position.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PinnedItemData &&
          runtimeType == other.runtimeType &&
          itemId == other.itemId &&
          kind == other.kind &&
          position == other.position;
}

class PlaybackStateData {
  final SongViewData song;
  final PlatformInt64 positionMs;
  final bool loopOne;

  const PlaybackStateData({
    required this.song,
    required this.positionMs,
    required this.loopOne,
  });

  @override
  int get hashCode => song.hashCode ^ positionMs.hashCode ^ loopOne.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaybackStateData &&
          runtimeType == other.runtimeType &&
          song == other.song &&
          positionMs == other.positionMs &&
          loopOne == other.loopOne;
}

class PlaylistEditRequest {
  final String playlistId;
  final String name;
  final PlaylistVisualEdit visual;

  const PlaylistEditRequest({
    required this.playlistId,
    required this.name,
    required this.visual,
  });

  @override
  int get hashCode => playlistId.hashCode ^ name.hashCode ^ visual.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaylistEditRequest &&
          runtimeType == other.runtimeType &&
          playlistId == other.playlistId &&
          name == other.name &&
          visual == other.visual;
}

class PlaylistViewData {
  final String id;
  final String name;
  final bool isSystem;
  final PlatformInt64 songCount;
  final String? iconKey;
  final String? imagePath;

  const PlaylistViewData({
    required this.id,
    required this.name,
    required this.isSystem,
    required this.songCount,
    this.iconKey,
    this.imagePath,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      isSystem.hashCode ^
      songCount.hashCode ^
      iconKey.hashCode ^
      imagePath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaylistViewData &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          isSystem == other.isSystem &&
          songCount == other.songCount &&
          iconKey == other.iconKey &&
          imagePath == other.imagePath;
}

@freezed
sealed class PlaylistVisualEdit with _$PlaylistVisualEdit {
  const PlaylistVisualEdit._();

  const factory PlaylistVisualEdit.keep() = PlaylistVisualEdit_Keep;
  const factory PlaylistVisualEdit.initials() = PlaylistVisualEdit_Initials;
  const factory PlaylistVisualEdit.icon({required String key}) =
      PlaylistVisualEdit_Icon;
  const factory PlaylistVisualEdit.image({
    required String originalSourcePath,
    required String croppedSourcePath,
    required ArtworkCropRectData crop,
  }) = PlaylistVisualEdit_Image;
}

class ScanConfig {
  final bool isDeezer;

  const ScanConfig({required this.isDeezer});

  @override
  int get hashCode => isDeezer.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScanConfig &&
          runtimeType == other.runtimeType &&
          isDeezer == other.isDeezer;
}

class SftpDownloadProgressData {
  final String jobId;
  final SftpDownloadStateData state;
  final String? currentName;
  final int filesCompleted;
  final int filesTotal;
  final BigInt bytesCompleted;
  final BigInt bytesTotal;
  final int failedFiles;
  final String? message;

  const SftpDownloadProgressData({
    required this.jobId,
    required this.state,
    this.currentName,
    required this.filesCompleted,
    required this.filesTotal,
    required this.bytesCompleted,
    required this.bytesTotal,
    required this.failedFiles,
    this.message,
  });

  @override
  int get hashCode =>
      jobId.hashCode ^
      state.hashCode ^
      currentName.hashCode ^
      filesCompleted.hashCode ^
      filesTotal.hashCode ^
      bytesCompleted.hashCode ^
      bytesTotal.hashCode ^
      failedFiles.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SftpDownloadProgressData &&
          runtimeType == other.runtimeType &&
          jobId == other.jobId &&
          state == other.state &&
          currentName == other.currentName &&
          filesCompleted == other.filesCompleted &&
          filesTotal == other.filesTotal &&
          bytesCompleted == other.bytesCompleted &&
          bytesTotal == other.bytesTotal &&
          failedFiles == other.failedFiles &&
          message == other.message;
}

enum SftpDownloadStateData {
  discovering,
  downloading,
  importing,
  completed,
  completedWithErrors,
  cancelled,
  failed;

  Future<bool> isTerminal() => RustLib.instance.api
      .crateApiModelsSftpDownloadStateDataIsTerminal(that: this);
}

class SftpEntryData {
  final String name;
  final String relativePath;
  final SftpEntryKindData kind;
  final BigInt? size;
  final PlatformInt64? modifiedAt;
  final bool downloaded;

  const SftpEntryData({
    required this.name,
    required this.relativePath,
    required this.kind,
    this.size,
    this.modifiedAt,
    required this.downloaded,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      relativePath.hashCode ^
      kind.hashCode ^
      size.hashCode ^
      modifiedAt.hashCode ^
      downloaded.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SftpEntryData &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          relativePath == other.relativePath &&
          kind == other.kind &&
          size == other.size &&
          modifiedAt == other.modifiedAt &&
          downloaded == other.downloaded;
}

enum SftpEntryKindData { file, directory, unsupported }

class SftpProfileData {
  final String id;
  final String name;
  final String host;
  final int port;
  final String username;
  final String rootPath;
  final String hostKeyFingerprint;
  final bool isSelected;

  const SftpProfileData({
    required this.id,
    required this.name,
    required this.host,
    required this.port,
    required this.username,
    required this.rootPath,
    required this.hostKeyFingerprint,
    required this.isSelected,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      host.hashCode ^
      port.hashCode ^
      username.hashCode ^
      rootPath.hashCode ^
      hostKeyFingerprint.hashCode ^
      isSelected.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SftpProfileData &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          host == other.host &&
          port == other.port &&
          username == other.username &&
          rootPath == other.rootPath &&
          hostKeyFingerprint == other.hostKeyFingerprint &&
          isSelected == other.isSelected;
}

@freezed
sealed class SongAudioEdit with _$SongAudioEdit {
  const SongAudioEdit._();

  const factory SongAudioEdit.keep() = SongAudioEdit_Keep;
  const factory SongAudioEdit.applyCrop({
    required String sourcePath,
    required PlatformInt64 startMs,
    required PlatformInt64 endMs,
  }) = SongAudioEdit_ApplyCrop;
  const factory SongAudioEdit.restoreOriginal() = SongAudioEdit_RestoreOriginal;
}

class SongCropData {
  final String originalAudioPath;
  final PlatformInt64 startMs;
  final PlatformInt64 endMs;

  const SongCropData({
    required this.originalAudioPath,
    required this.startMs,
    required this.endMs,
  });

  @override
  int get hashCode =>
      originalAudioPath.hashCode ^ startMs.hashCode ^ endMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SongCropData &&
          runtimeType == other.runtimeType &&
          originalAudioPath == other.originalAudioPath &&
          startMs == other.startMs &&
          endMs == other.endMs;
}

class SongEditRequest {
  final String songId;
  final String title;
  final String primaryArtist;
  final List<String> featuredArtists;
  final PlatformInt64 trackNum;
  final PlatformInt64 discNum;
  final AlbumChoice album;
  final CoverArtEdit cover;
  final SongAudioEdit audio;

  const SongEditRequest({
    required this.songId,
    required this.title,
    required this.primaryArtist,
    required this.featuredArtists,
    required this.trackNum,
    required this.discNum,
    required this.album,
    required this.cover,
    required this.audio,
  });

  @override
  int get hashCode =>
      songId.hashCode ^
      title.hashCode ^
      primaryArtist.hashCode ^
      featuredArtists.hashCode ^
      trackNum.hashCode ^
      discNum.hashCode ^
      album.hashCode ^
      cover.hashCode ^
      audio.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SongEditRequest &&
          runtimeType == other.runtimeType &&
          songId == other.songId &&
          title == other.title &&
          primaryArtist == other.primaryArtist &&
          featuredArtists == other.featuredArtists &&
          trackNum == other.trackNum &&
          discNum == other.discNum &&
          album == other.album &&
          cover == other.cover &&
          audio == other.audio;
}

class SongViewData {
  final String id;
  final String title;
  final String primaryArtist;
  final List<String> featuredArtists;
  final String? coverPath;
  final String filePath;
  final PlatformInt64 trackNum;
  final PlatformInt64 discNum;
  final String album;
  final String albumId;
  final List<String> albumArtists;
  final String? songCoverPath;
  final SongCropData? crop;

  const SongViewData({
    required this.id,
    required this.title,
    required this.primaryArtist,
    required this.featuredArtists,
    this.coverPath,
    required this.filePath,
    required this.trackNum,
    required this.discNum,
    required this.album,
    required this.albumId,
    required this.albumArtists,
    this.songCoverPath,
    this.crop,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      primaryArtist.hashCode ^
      featuredArtists.hashCode ^
      coverPath.hashCode ^
      filePath.hashCode ^
      trackNum.hashCode ^
      discNum.hashCode ^
      album.hashCode ^
      albumId.hashCode ^
      albumArtists.hashCode ^
      songCoverPath.hashCode ^
      crop.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SongViewData &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          primaryArtist == other.primaryArtist &&
          featuredArtists == other.featuredArtists &&
          coverPath == other.coverPath &&
          filePath == other.filePath &&
          trackNum == other.trackNum &&
          discNum == other.discNum &&
          album == other.album &&
          albumId == other.albumId &&
          albumArtists == other.albumArtists &&
          songCoverPath == other.songCoverPath &&
          crop == other.crop;
}
