// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'scanner.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CLibrary>>
abstract class CLibrary implements RustOpaqueInterface {
  Future<void> addSongToPlaylist({
    required String playlistId,
    required String songId,
  });

  Future<String> createPlaylist({required String name});

  Future<void> deleteAlbum({required String id});

  Future<void> deletePlaylist({required String id});

  /// Remove a scan path and every song indexed beneath it. Returns the
  /// number of songs purged so the UI can surface it in a toast.
  Future<int> deleteScanPath({required String path});

  Future<void> deleteSong({required String id});

  Future<List<AlbumViewData>> getAlbumsArtistFeaturedOn({
    required String artistId,
  });

  Future<List<AlbumViewData>> getAlbumsByArtistId({required String artistId});

  Future<List<AlbumViewData>> getAlbumsPaginated({
    required int offset,
    required int limit,
  });

  Future<ArtistViewData?> getArtistById({required String id});

  Future<List<ArtistViewData>> getArtistsPaginated({
    required int offset,
    required int limit,
  });

  Future<List<String>> getLikedSongIds();

  Future<String?> getLikedSongsPlaylistId();

  Future<List<PinnedItemData>> getPinnedItems();

  Future<List<PlaylistViewData>> getPlaylistsPaginated({
    required int offset,
    required int limit,
  });

  Future<List<SongViewData>> getRecentlyPlayed({required int limit});

  Future<List<String>> getScanPaths();

  Future<SongViewData?> getSongById({required String id});

  Future<List<SongViewData>> getSongsArtistFeaturedOn({
    required String artistId,
  });

  Future<List<SongViewData>> getSongsByAlbumId({required String albumId});

  Future<List<SongViewData>> getSongsInPlaylist({required String playlistId});

  Future<List<SongViewData>> getSongsPaginated({
    required int offset,
    required int limit,
  });

  int getTotalAlbums();

  int getTotalArtists();

  int getTotalPlaylists();

  int getTotalSongs();

  /// Open (or create) the SQLite database at `db_path` and ensure the covers
  /// directory exists. Must be called once from Dart before any other method.
  static Future<CLibrary> init({
    required String dbPath,
    required String coversDir,
    required String baseDir,
  }) => RustLib.instance.api.crateApiScannerCLibraryInit(
    dbPath: dbPath,
    coversDir: coversDir,
    baseDir: baseDir,
  );

  Future<PlaybackStateData?> loadPlaybackState();

  Future<void> movePinnedItem({
    required String itemId,
    required String kind,
    required int newIndex,
  });

  Future<void> pinItem({required String itemId, required String kind});

  Future<void> recordPlay({required String songId});

  Future<void> removeSongFromPlaylist({
    required String playlistId,
    required String songId,
  });

  Future<void> resetLibrary();

  Future<void> savePlaybackState({
    String? songId,
    required PlatformInt64 positionMs,
    required bool loopOne,
  });

  /// Recursively scan `path` for audio files and write their metadata into
  /// SQLite. Files already present (matched by `file_path`) are skipped.
  Future<void> scanDirectory({required String path, required Config config});

  Future<List<AlbumViewData>> searchAlbums({
    required String query,
    required int limit,
  });

  Future<List<ArtistViewData>> searchArtists({
    required String query,
    required int limit,
  });

  Future<List<PlaylistViewData>> searchPlaylists({
    required String query,
    required int limit,
  });

  Future<List<SongViewData>> searchSongs({
    required String query,
    required int limit,
  });

  /// Fork an album onto a freshly-created artist row with the same name.
  /// Returns the new artist's id. Used by the UI to resolve ambiguity when
  /// the scanner merged two distinct same-named artists into one row.
  Future<String> splitAlbumToNewArtist({required String albumId});

  Future<void> unpinItem({required String itemId, required String kind});

  Future<AlbumViewData> updateAlbum({required AlbumEditRequest request});

  Future<ArtistViewData> updateArtistImage({
    required String artistId,
    required CoverArtEdit cover,
  });

  Future<PlaylistViewData> updatePlaylist({
    required PlaylistEditRequest request,
  });

  Future<SongViewData> updateSong({required SongEditRequest request});
}

@freezed
sealed class AlbumChoice with _$AlbumChoice {
  const AlbumChoice._();

  const factory AlbumChoice.existing({required String albumId}) =
      AlbumChoice_Existing;
  const factory AlbumChoice.new_({
    required String title,
    required List<String> artists,
  }) = AlbumChoice_New;
}

class AlbumEditRequest {
  final String albumId;
  final String title;
  final List<String> artists;
  final CoverArtEdit cover;

  const AlbumEditRequest({
    required this.albumId,
    required this.title,
    required this.artists,
    required this.cover,
  });

  @override
  int get hashCode =>
      albumId.hashCode ^ title.hashCode ^ artists.hashCode ^ cover.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AlbumEditRequest &&
          runtimeType == other.runtimeType &&
          albumId == other.albumId &&
          title == other.title &&
          artists == other.artists &&
          cover == other.cover;
}

/// UI-ready album shape. `artist` is the resolved album-artist name.
class AlbumViewData {
  final String id;
  final String title;
  final String artist;
  final String? coverPath;
  final PlatformInt64 songCount;
  final List<String> artists;

  const AlbumViewData({
    required this.id,
    required this.title,
    required this.artist,
    this.coverPath,
    required this.songCount,
    required this.artists,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      artist.hashCode ^
      coverPath.hashCode ^
      songCount.hashCode ^
      artists.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AlbumViewData &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          artist == other.artist &&
          coverPath == other.coverPath &&
          songCount == other.songCount &&
          artists == other.artists;
}

/// UI-ready artist shape. `cover_path` is a representative album cover for
/// the artist (may be `None` if no albums have covers yet).
class ArtistViewData {
  final String id;
  final String name;
  final String? coverPath;
  final PlatformInt64 albumCount;
  final PlatformInt64 songCount;
  final String? customCoverPath;

  const ArtistViewData({
    required this.id,
    required this.name,
    this.coverPath,
    required this.albumCount,
    required this.songCount,
    this.customCoverPath,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      coverPath.hashCode ^
      albumCount.hashCode ^
      songCount.hashCode ^
      customCoverPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArtistViewData &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          coverPath == other.coverPath &&
          albumCount == other.albumCount &&
          songCount == other.songCount &&
          customCoverPath == other.customCoverPath;
}

class Config {
  final bool isDeezer;

  const Config({required this.isDeezer});

  @override
  int get hashCode => isDeezer.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Config &&
          runtimeType == other.runtimeType &&
          isDeezer == other.isDeezer;
}

@freezed
sealed class CoverArtEdit with _$CoverArtEdit {
  const CoverArtEdit._();

  const factory CoverArtEdit.keep() = CoverArtEdit_Keep;
  const factory CoverArtEdit.remove() = CoverArtEdit_Remove;
  const factory CoverArtEdit.replace({required String sourcePath}) =
      CoverArtEdit_Replace;
}

/// UI-ready pinned item for the quick-play sidebar.
class PinnedItemData {
  final String itemId;
  final String kind;
  final PlatformInt64 position;

  const PinnedItemData({
    required this.itemId,
    required this.kind,
    required this.position,
  });

  @override
  int get hashCode => itemId.hashCode ^ kind.hashCode ^ position.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PinnedItemData &&
          runtimeType == other.runtimeType &&
          itemId == other.itemId &&
          kind == other.kind &&
          position == other.position;
}

/// UI-ready playback state used to resume the MediaBar on relaunch.
class PlaybackStateData {
  final SongViewData song;
  final PlatformInt64 positionMs;
  final bool loopOne;

  const PlaybackStateData({
    required this.song,
    required this.positionMs,
    required this.loopOne,
  });

  @override
  int get hashCode => song.hashCode ^ positionMs.hashCode ^ loopOne.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaybackStateData &&
          runtimeType == other.runtimeType &&
          song == other.song &&
          positionMs == other.positionMs &&
          loopOne == other.loopOne;
}

class PlaylistEditRequest {
  final String playlistId;
  final String name;
  final PlaylistVisualEdit visual;

  const PlaylistEditRequest({
    required this.playlistId,
    required this.name,
    required this.visual,
  });

  @override
  int get hashCode => playlistId.hashCode ^ name.hashCode ^ visual.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaylistEditRequest &&
          runtimeType == other.runtimeType &&
          playlistId == other.playlistId &&
          name == other.name &&
          visual == other.visual;
}

/// UI-ready playlist shape.
class PlaylistViewData {
  final String id;
  final String name;
  final bool isSystem;
  final PlatformInt64 songCount;
  final String? iconKey;
  final String? imagePath;

  const PlaylistViewData({
    required this.id,
    required this.name,
    required this.isSystem,
    required this.songCount,
    this.iconKey,
    this.imagePath,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      isSystem.hashCode ^
      songCount.hashCode ^
      iconKey.hashCode ^
      imagePath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaylistViewData &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          isSystem == other.isSystem &&
          songCount == other.songCount &&
          iconKey == other.iconKey &&
          imagePath == other.imagePath;
}

@freezed
sealed class PlaylistVisualEdit with _$PlaylistVisualEdit {
  const PlaylistVisualEdit._();

  const factory PlaylistVisualEdit.keep() = PlaylistVisualEdit_Keep;
  const factory PlaylistVisualEdit.initials() = PlaylistVisualEdit_Initials;
  const factory PlaylistVisualEdit.icon({required String key}) =
      PlaylistVisualEdit_Icon;
  const factory PlaylistVisualEdit.image({required String sourcePath}) =
      PlaylistVisualEdit_Image;
}

class SongEditRequest {
  final String songId;
  final String title;
  final String primaryArtist;
  final List<String> featuredArtists;
  final PlatformInt64 trackNum;
  final PlatformInt64 discNum;
  final AlbumChoice album;
  final CoverArtEdit cover;

  const SongEditRequest({
    required this.songId,
    required this.title,
    required this.primaryArtist,
    required this.featuredArtists,
    required this.trackNum,
    required this.discNum,
    required this.album,
    required this.cover,
  });

  @override
  int get hashCode =>
      songId.hashCode ^
      title.hashCode ^
      primaryArtist.hashCode ^
      featuredArtists.hashCode ^
      trackNum.hashCode ^
      discNum.hashCode ^
      album.hashCode ^
      cover.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SongEditRequest &&
          runtimeType == other.runtimeType &&
          songId == other.songId &&
          title == other.title &&
          primaryArtist == other.primaryArtist &&
          featuredArtists == other.featuredArtists &&
          trackNum == other.trackNum &&
          discNum == other.discNum &&
          album == other.album &&
          cover == other.cover;
}

/// Flattened, UI-ready view of a song. All names are resolved strings — the
/// frontend never sees IDs for artists/albums.
class SongViewData {
  final String id;
  final String title;
  final String primaryArtist;
  final List<String> featuredArtists;
  final String? coverPath;
  final String filePath;
  final PlatformInt64 trackNum;
  final PlatformInt64 discNum;
  final String album;
  final String albumId;
  final List<String> albumArtists;
  final String? songCoverPath;

  const SongViewData({
    required this.id,
    required this.title,
    required this.primaryArtist,
    required this.featuredArtists,
    this.coverPath,
    required this.filePath,
    required this.trackNum,
    required this.discNum,
    required this.album,
    required this.albumId,
    required this.albumArtists,
    this.songCoverPath,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      primaryArtist.hashCode ^
      featuredArtists.hashCode ^
      coverPath.hashCode ^
      filePath.hashCode ^
      trackNum.hashCode ^
      discNum.hashCode ^
      album.hashCode ^
      albumId.hashCode ^
      albumArtists.hashCode ^
      songCoverPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SongViewData &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          primaryArtist == other.primaryArtist &&
          featuredArtists == other.featuredArtists &&
          coverPath == other.coverPath &&
          filePath == other.filePath &&
          trackNum == other.trackNum &&
          discNum == other.discNum &&
          album == other.album &&
          albumId == other.albumId &&
          albumArtists == other.albumArtists &&
          songCoverPath == other.songCoverPath;
}
