// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `assign_album_cover`, `get_artist_uuid`, `handle_album`, `handle_artist`, `new`, `tag_value_to_i64`, `update_album_field`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AlbumField`, `Album`, `ArtistGroup`, `Artist`, `MetadataCache`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `hash`

Future<void> extractMetadata({
  required CLibrary library_,
  required Config config,
  required String path,
}) => RustLib.instance.api.crateApiScannerExtractMetadata(
  library_: library_,
  config: config,
  path: path,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CLibrary>>
abstract class CLibrary implements RustOpaqueInterface {
  Future<void> addSong({required Config config, required String path});

  CSongDart? currentSong();

  String? getArtist({required String id});

  Future<CSongDart?> getSongById({required String id});

  Future<CSongDart?> getSongByIndex({required BigInt index});

  factory CLibrary() => RustLib.instance.api.crateApiScannerCLibraryNew();

  BigInt numSongs();

  Future<CSongDart?> playSong({required String id});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CSong>>
abstract class CSong implements RustOpaqueInterface {
  Future<ArtistGroupDart> getArtists();

  Future<String> getId();

  Future<String> getTitle();
}

class ArtistGroupDart {
  final String leading;
  final List<String> features;

  const ArtistGroupDart({required this.leading, required this.features});

  Future<void> getArtistStr() => RustLib.instance.api
      .crateApiScannerArtistGroupDartGetArtistStr(that: this);

  @override
  int get hashCode => leading.hashCode ^ features.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArtistGroupDart &&
          runtimeType == other.runtimeType &&
          leading == other.leading &&
          features == other.features;
}

class CImage {
  final Uint8List data;
  final String mimeType;

  const CImage({required this.data, required this.mimeType});

  @override
  int get hashCode => data.hashCode ^ mimeType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CImage &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          mimeType == other.mimeType;
}

class CSongDart {
  final String id;
  final String title;
  final ArtistGroupDart artists;
  final PlatformInt64 trackNum;
  final PlatformInt64 discNum;
  final String album;
  final CImage? cover;
  final String path;

  const CSongDart({
    required this.id,
    required this.title,
    required this.artists,
    required this.trackNum,
    required this.discNum,
    required this.album,
    this.cover,
    required this.path,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      artists.hashCode ^
      trackNum.hashCode ^
      discNum.hashCode ^
      album.hashCode ^
      cover.hashCode ^
      path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CSongDart &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          artists == other.artists &&
          trackNum == other.trackNum &&
          discNum == other.discNum &&
          album == other.album &&
          cover == other.cover &&
          path == other.path;
}

class Config {
  final bool isDeezer;

  const Config({required this.isDeezer});

  @override
  int get hashCode => isDeezer.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Config &&
          runtimeType == other.runtimeType &&
          isDeezer == other.isDeezer;
}
